services:
  user-service:
    build:
      context: userService
    image: high-load-server
    container_name: user-server
    depends_on:
      - mongodb
    env_file:
      - ./userService/java.env
    environment:
      SERVER_PORT: 8080
      MONGODB_HOST: mongodb
      MONGODB_PORT: 27017
      MONGO_DB: highLoadDb
    tty: true

    ports:
      - "8080:8080"
      - "5007:5005"
    stdin_open: true
    networks:
      server-network:
        ipv4_address: 10.0.15.99

  event-service:
    build:
      context: eventService
    image: high-load-server
    container_name: event-server
    depends_on:
      - postgres
    env_file:
      - ./eventService/java.env
    environment:
      SERVER_PORT: 8080
      POSTGRES_DATASOURCE_URL: jdbc:postgresql://10.0.15.98:5432/events
      POSTGRES_PASSWORD: example
    tty: true

    ports:
      - "8081:8080"
    stdin_open: true
    networks:
      server-network:
        ipv4_address: 10.0.15.100

  mongodb:
    image: mongo:8.0.4
    container_name: mongodb
    tty: true
    ports:
      - "27077:27017"
    stdin_open: true
    entrypoint: mongod --bind_ip_all
    volumes:
      - ./mongo-db/mongodb_data:/data/db
    networks:
      server-network:

  postgres:
    image: postgres:17.4
    container_name: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    volumes:
      - ./postgres-db/init.sql:/docker-entrypoint-initdb.d/init.sql
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_DB: events
      POSTGRES_PASSWORD: example
    networks:
      server-network:
        ipv4_address: 10.0.15.98

#  high-load-web:
#    build:
#      context: web
#    image: high-load-server
#    container_name: high-load-server
#    tty: true
#    stdin_open: true
#    ports:
#      - "3000:3000"
#    networks:
#      server-network:

networks:
  server-network:
    ipam:
      driver: default
      config:
        - subnet: 10.0.15.0/24