services:
  user-service:
    build:
      context: serverSide
    image: high-load-server
    container_name: high-load-server
    depends_on:
      - mongodb
    env_file:
      - ./userService/java.env
    environment:
      SERVER_PORT: 8080
      MONGODB_HOST: mongodb
      MONGODB_PORT: 27017
      MONGO_DB: highLoadDb
    tty: true

    ports:
      - "8080:8080"
      - "5007:5005"
    stdin_open: true
    networks:
      server-network:
        ipv4_address: 10.0.15.99

  mongodb:
    image: mongo:8.0.4
    container_name: mongodb
    tty: true
    ports:
      - "27077:27017"
    stdin_open: true
    entrypoint: mongod --bind_ip_all
    volumes:
      - ./mongo-db/mongodb_data:/data/db
    networks:
      server-network:

  postgres:
    image: postgres:17.4
    container_name: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: example

#  high-load-web:
#    build:
#      context: web
#    image: high-load-server
#    container_name: high-load-server
#    tty: true
#    stdin_open: true
#    ports:
#      - "3000:3000"
#    networks:
#      server-network:

networks:
  server-network:
    ipam:
      driver: default
      config:
        - subnet: 10.0.15.0/24