spring:
  application:
    name: events-service
  datasource:
    url: ${POSTGRES_DATASOURCE_URL}
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  cache:
    type: redis
  data.redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT:6379}
    key-prefix: "events::cache::"

logging.level.ua: INFO

security:
  jwt:
    secret-key: ${JWT_SECRET_KEY}

springdoc:
  swagger-ui:
    path: /events/swagger/ui
  api-docs:
    path: /events/swagger/api-docs

images-bucket-name: images-bucket

minio:
  url: ${MINIO_URL}
  public-url: ${MINIO_PUBLIC_URL}
  access-key: ${MINIO_ACCESS_KEY}
  secret-key: ${MINIO_SECRET_KEY}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true
