import AppShell from "@/components/common/AppShell/AppShell";
import type { Metadata } from "next";
import "./globals.css";
import '@mantine/core/styles.css';

import { createTheme, MantineProvider } from '@mantine/core';

const theme = createTheme({});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
      <MantineProvider theme={theme}>
          {children}
      </MantineProvider>
      </body>
    </html>
  );
}
