spring:
  application:
    name: orders-service

springdoc:
  swagger-ui:
    path: /orders/swagger/ui
  api-docs:
    path: /orders/swagger/api-docs

spring.data.mongodb:
  host: ${MONGODB_HOST:localhost}
  port: ${MONGODB_PORT:27017}
  database: ${MONGO_DB:highLoadDb}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true