spring:
  application:
    name: orders-service
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    virtual-host: ${RABBITMQ_VHOST:orders}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:admin}
    password: ${RABBITMQ_PASSWORD:admin}

# Rabbitmq queues
booking.exchange: booking.exchange
booking.defer.queue: booking.defer.queue
booking.dead.queue: booking.dead.queue
booking.ttl: 10000 # 10 seconds in ms
booking.routing-key: booked
booking.expired.routing-key: expired

springdoc:
  swagger-ui:
    path: /orders/swagger/ui
  api-docs:
    path: /orders/swagger/api-docs

spring.data.mongodb:
  host: ${MONGODB_HOST:localhost}
  port: ${MONGODB_PORT:27077}
  database: ${MONGO_DB:highLoadDb}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true